window.TX_RECEIPTS_NETWORKS = [
  {
    id: "base",
    name: "Base",
    family: "evm",
    chainId: "0x2105",
    decimalChainId: "8453",
    rpcUrl: "https://mainnet.base.org",
    explorerUrl: "https://basescan.org",
    blockscoutUrl: "https://base.blockscout.com",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  },
  {
    id: "ethereum",
    name: "Ethereum",
    family: "evm",
    chainId: "0x1",
    decimalChainId: "1",
    rpcUrl: "https://ethereum-rpc.publicnode.com",
    explorerUrl: "https://etherscan.io",
    blockscoutUrl: "https://eth.blockscout.com",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  },
  {
    id: "optimism",
    name: "Optimism",
    family: "evm",
    chainId: "0xa",
    decimalChainId: "10",
    rpcUrl: "https://mainnet.optimism.io",
    explorerUrl: "https://optimistic.etherscan.io",
    blockscoutUrl: "https://optimism.blockscout.com",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  },
  {
    id: "arbitrum",
    name: "Arbitrum One",
    family: "evm",
    chainId: "0xa4b1",
    decimalChainId: "42161",
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    explorerUrl: "https://arbiscan.io",
    blockscoutUrl: "https://arbitrum.blockscout.com",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  },
  {
    id: "polygon",
    name: "Polygon",
    family: "evm",
    chainId: "0x89",
    decimalChainId: "137",
    rpcUrl: "https://polygon-rpc.com",
    explorerUrl: "https://polygonscan.com",
    blockscoutUrl: "https://polygon.blockscout.com",
    nativeCurrency: { name: "POL", symbol: "POL", decimals: 18 },
  },
  {
    id: "solana",
    name: "Solana",
    family: "solana",
    cluster: "mainnet-beta",
    rpcUrl: "https://solana-rpc.debridge.finance",
    rpcUrls: [
      "https://solana-rpc.debridge.finance",
      "https://solana-rpc.publicnode.com",
    ],
    explorerUrl: "https://solscan.io",
    nativeCurrency: { name: "Solana", symbol: "SOL", decimals: 9 },
  },
];
